# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!

[plugins]
"rocks-git.nvim" = "1.3.0"
"rocks.nvim" = "2.19.1"
cmp-buffer = "scm"
cmp-nvim-lsp = "scm"
nvim-cmp = "0.0.1"
nvim-lspconfig = "0.1.7"
nvim-treesitter = "0.9.2"
tree-sitter-lua = "scm"
tree-sitter-markdown = "scm"

[plugins.vim-surround]
git = "tpope/vim-surround"
rev = "v2.2^{}"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2^{}"

[plugins.vim-over]
git = "osyo-manga/vim-over"

[plugins.emmet-vim]
git = "mattn/emmet-vim"

[plugins.vim-indent-object]
git = "michaeljsmith/vim-indent-object"
rev = "1.1.2"

[plugins."pytest.vim"]
git = "alfredodeza/pytest.vim"

[plugins.Zenburn]
git = "jnurmine/Zenburn"
rev = "v2.29"

[plugins.vim-airline]
git = "vim-airline/vim-airline"
rev = "v0.9"

[plugins.vim-airline-themes]
git = "vim-airline/vim-airline-themes"

[plugins.coq_nvim]
git = "ms-jpq/coq_nvim"
