# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
plugins_dir="plugin-configs/"

[plugins]
"lualine.nvim" = "scm"
"plenary.nvim" = "scm"
"rocks-config.nvim" = "3.1.2"
"rocks-git.nvim" = "2.5.6"
"rocks.nvim" = "2.46.1"
nvim-lspconfig = "2.5.0"

[plugins.vim-surround]
git = "tpope/vim-surround"
rev = "v2.2^{}"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2^{}"

[plugins.vim-over]
git = "osyo-manga/vim-over"

[plugins.emmet-vim]
git = "mattn/emmet-vim"

[plugins.vim-indent-object]
git = "michaeljsmith/vim-indent-object"
rev = "1.1.2"

[plugins."pytest.vim"]
git = "alfredodeza/pytest.vim"

[plugins.coq_nvim]
git = "ms-jpq/coq_nvim"

[plugins."zenburn.nvim"]
git = "phha/zenburn.nvim"

[plugins."none-ls.nvim"]
git = "nvimtools/none-ls.nvim"
