set nocompatible                "no vi compatibility

syntax on                       "enable syntax highlighting
filetype plugin on              "enable plugins for filetypes

set title
set path=**                     "make file search recursive
set wildmenu                    "enable cool menu
set mouse=a                     "get mouse working on mouse-capable terminals
set backspace=indent,eol,start  "make backspace work everywhere
set laststatus=2
set ttimeoutlen=0               "no delay when going back into normal mode
set clipboard=unnamedplus       "make vim clipboard the same as the system one
if !has('nvim')
    set clipboard^=autoselect       "copy on selection like in X
endif
set nofoldenable                "disable default folding of text
set nobackup                    "no annoying backups of files
set number                      "line numbers
set ruler                       "show row and column on bottom right
set guicursor=
"set autochdir                   "change directory to where the file is

set expandtab                   "spaces instead of tab
set tabstop=4                   "tabwidth is 4 spaces
set shiftwidth=4                "indent by 4 with >> and <<
set autoindent                  "start nextline indented

set hlsearch                    "highlight searches
set incsearch                   "do incremental searching
set showmatch                   "jump to matches when entering regexp
set ignorecase                  "ignore case on search
set smartcase                   "uppercase forces search casing

set completeopt-=preview        "no preview window for completion

set listchars=tab:——,space:·

command! -nargs=1 Source runtime! conf.d/<args>

Source plugins.vim
Source custom.vim
Source plugin-setup.vim
Source keymaps.vim
