#!/bin/bash

BATT=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/ADP1/online)

if [[ $STATUS == 1 ]]
then
    symbol=
elif (($BATT <= 25))
then
    symbol=
elif (($BATT <= 50))
then
    symbol=
elif (($BATT <= 75))
then
    symbol=
else
    symbol=
fi

notify-send -t 1000 ' ' "$symbol $BATT%"
