#!/bin/bash

set -euo pipefail

faketty () (
    export TERM=xterm
    script -qfec "$(printf "%q " "$@")" /dev/null
)


ascii_escape_to_pango() {
    sed -e 's#'$(echo -e '\033\[7m')'#<span foreground="black" background="white">#g' \
        -e 's#'$(echo -e '\033\[27m')'#</span>#g'
}


main() {
    local nmonths="${1:-1}"

    notify-send ' ' "$(faketty cal -n "${nmonths}" -S | ascii_escape_to_pango)"
}

main "$@"
