#!/bin/bash

PREFIX="${HOME}/.config"

function get-profile {
    echo ${PREFIX}/chromium-* |
    sed "s#${PREFIX}/chromium-##g" |
    rofi -dmenu -p 'Profile:' -sep ' '
}

PROFILE="$1"

if [[ -z "${PROFILE}" ]]
then
    PROFILE=$(get-profile)
fi

exec chromium --user-data-dir="${PREFIX}/chromium-${PROFILE}" ${@:2}
