#!/bin/bash
function iterative_check {
    ids=$(xprop -root |
          grep '_NET_CLIENT_LIST(WINDOW)' |
          sed 's/.*#\s//' |
          sed 's/, /\n/g')
    for id in ${ids}
    do
        xprop_output=$(xprop -id "${id}" 2> /dev/null)
        if echo "${xprop_output}" | grep -q "$1"
        then
            echo "${xprop_output}"
        fi
    done
}

function check {
    if xprop -name "$1" 2> /dev/null
    then
        return
    else
        iterative_check "$1"
    fi
}

WINNAME="urxvt-console"

if which st > /dev/null
then
    term="st -g 80x1+1+1 -n ${WINNAME}"
else
    term="urxvt -geometry 80x1-0-0 -name ${WINNAME}"
fi

xprop_output=$(check "${WINNAME}")
is_showing=$(echo ${xprop_output} | grep Withdrawn)

if [[ -z ${xprop_output} ]]
then
    $term & disown
    exit 0
elif [[ -z ${is_showing} ]]
then
    i3-msg '[instance="'${WINNAME}'"]' move scratchpad
else
    i3-msg '[instance="'${WINNAME}'"]' scratchpad show
fi
