#!/bin/bash
function rename {
    echo -ne "\033]0;$1\007"
    sleep 0.01
    if i3 --get-socketpath > /dev/null
    then
        i3-msg mode default > /dev/null
    fi
}

rename VIM
$(wrap "$0") "$@"
rename st
