#!/bin/bash

set -eou pipefail

BROWSER="${BROWSER:-}"

BROWSERS=(
    $BROWSER
    chromium
    google-chrome
    google-chrome-stable
    firefox
)

main() {
    local browser

    for i in "${BROWSERS[@]}"
    do
        if which $i
        then
            browser="$i"
            break
        fi
    done

    exec $i $@
}

main $@
