#!/bin/bash

while getopts ":sc" flag
do
    case "${flag}" in
        s)
            FLAGS="-s"
            ;;
        c)
            CLIP=1
            ;;
    esac
done

save-or-clip() {
    if [[ "${CLIP}" == 1 ]]
    then
        xclip -t image/png "${1}" -selection clipboard
        xclip -t image/png "${1}"
        rm "${1}"
    else
        mv "${1}" "${HOME}/.screenshots/"$(dmenu -p "Filename (.png): " < /dev/null)".png"
    fi
}

TMP="$(mktemp --suffix=.png)" &&
maim -u ${FLAGS} "$TMP" &&
save-or-clip "$TMP"
