#!/bin/sh

# tardefuse.sh

# The MIT License (MIT)

# Copyright (c) 2014 Tarcísio E. M. Crocomo

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

FULLPATH="$(readlink -f $1)"

if [[ ! -f "${FULLPATH}" ]]
then
    echo "file $1 not found" 1>&2
    exit 1
fi

NPREFIXES="$(tar -tf $1 | sed -e 's/\/.*$//' | uniq | wc -l)"

if [[ "${NPREFIXES}" != "1" ]]
then
    echo "'tis a bomb!" 1>&2
    DIRNAME="$(basename "${FULLPATH}" | sed s/.tar.*$//g)"
    mkdir "${DIRNAME}"
    cd "${DIRNAME}"
fi

tar -xvf "${FULLPATH}"
