#!/bin/bash

KBMAP=$(setxkbmap -query | grep variant | cut -d ':' -f 2 | sed -e 's/\s//g')

case "$KBMAP" in
    'dvorak-mod')
        setxkbmap br abnt2
        ;;
    *)
        setxkbmap br dvorak-mod
        ;;
esac

setupkeys
