#!/bin/bash
if [ -e ${HOME}/.xinitrc_before ]
then
    source ${HOME}/.xinitrc_before
fi

if [ -e ${HOME}/.bash_profile ]
then
    source ${HOME}/.bash_profile
fi

if [ -e ${HOME}/.shutils/base-vars.sh ]
then
    source ${HOME}/.shutils/base-vars.sh
fi

$BGCMD $WALLPAPER

if which $COMPMGR
then
    $COMPMGR
fi

if [ -e ${HOME}/.xinitrc_after ]
then
    source ${HOME}/.xinitrc_after
fi
