#!/bin/bash

# LightDM on Arch tries to source this with /bin/sh. Eew!
[[ -z "${POSIXLY_CORRECT}" ]] || return

source-if-exists() {
    [[ -e "${1}" ]] && source "${1}"
}

command-available() {
    which "${1}" > /dev/null 2>&1
}

call-if-available()
{
    local command="${1}"

    command-available "${command}" && "$@"
}

source-if-exists "${HOME}/.profile"

# Sane defaults. Can be overriden by ~/.xinitrc_before

BGCMD=hsetroot
BGCMD_ARGS="-full"
COMPMGR=picom
COMPMGR_ARGS="-b"

source-if-exists "${HOME}/.xinitrc_before"

call-if-available "${BGCMD}" ${BGCMD_ARGS} "${WALLPAPER}"
call-if-available "${COMPMGR}" ${COMPMGR_ARGS}

source-if-exists "${HOME}/.xinitrc_after"

WM="${WM:-i3}"

systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
systemctl --no-block --user start xsession.target

"${WM}"
