#!/bin/bash

# LightDM on Arch tries to source this with /bin/sh. Eew!
[[ -z "${POSIXLY_CORRECT}" ]] || return

source-if-exists() {
    [[ -e "${1}" ]] && source "${1}"
}

source-if-exists "${HOME}/.xinitrc_before"
source-if-exists "${HOME}/.profile"

$BGCMD $BGCMD_ARGS $WALLPAPER

which "${COMPMGR}" > /dev/null 2>&1 && $COMPMGR $COMPMGR_ARGS

source-if-exists ${HOME}/.xinitrc_after

WM="${WM:-i3}"

$WM &

systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
systemctl --no-block --user start xsession.target

wait
