#!/bin/bash

if [ -n $POSIXLY_CORRECT ]
then
    # LightDM on Arch tries to source this with /bin/sh. Eew!
    return
fi

if [ -e ${HOME}/.xinitrc_before ]
then
    source ${HOME}/.xinitrc_before
fi

if [ -e ${HOME}/.bash_profile ]
then
    source ${HOME}/.bash_profile
fi

if [ -e ${HOME}/.shutils/base-vars.sh ]
then
    source ${HOME}/.shutils/base-vars.sh
fi

$BGCMD $WALLPAPER

if which $COMPMGR
then
    $COMPMGR
fi

if [ -e ${HOME}/.xinitrc_after ]
then
    source ${HOME}/.xinitrc_after
fi

if [ -z "$WM" ]
then
    WM=i3
fi

exec $WM
