HISTFILE=~/.histfile
HISTSIZE=32000
SAVEHIST=32000
DIRSTACKSIZE=8
KEYTIMEOUT=1

setopt HIST_IGNORE_SPACE

# define DIRCOLORS
PACKAGES=${HOME}/.zsh

# get the require function
source ${PACKAGES}/init.zsh &> /dev/null || return

require dircolors
require plugins
require prompt
require keyboard
require completion
require aliases
require python-utils
require custom-cd
require ssh-agent

require-if-exists localdefs || true
cd .
