if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

# get the require function
PACKAGES=${HOME}/.shutils
source ${PACKAGES}/init.sh &> /dev/null || return

require-if-exists base

require aliases
require completion
require custom-cd
require dircolors
require prompt
require python-utils
require ssh-agent

require-if-exists plugins
require-if-exists keyboard
require-if-exists localdefs
cd .
